name:                simple-json-api-haskell
version:             0.1.0.0
github:              "cdimitroulas/simple-json-api-haskell"
license:             BSD3
author:              "Christos Dimitroulas"
copyright:           "2021 Christos Dimitroulas"

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- aeson
- containers
- mtl
- text
- scotty

default-extensions:
  - DeriveGeneric
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - OverloadedStrings

executables:
  simple-json-api-haskell-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
